@startuml
top to bottom direction
package "picture_frame" {
    [viewer_display] as v
    () "show image" as show_image
    () "display switch" as display_switch
    [controller] as c
    () "service interface" as interface
    frame "interfaces" {
        [browser]
        [Home Assistant]
        [keyboard]
    }
    [model] as m
    database "sqlite" as db{
        folder "config kv" as kv_folder {
            [viewer]
            [model]
            [mqtt]
            [webserver]
        }
        note bottom of kv_folder
            Maybe sqlite json extension
        end note
        folder "images" as image_folder {
            [meta data]
            [address]
        }
        note bottom of image_folder
            Maybe sqlite extension-functions.c extension
            for sin, cos
        end note
    }


    show_image-up-v
    display_switch-up-v
    interface-down-c
    [browser]-down->interface :  http
    [Home Assistant]-down->interface :  mqtt
    [keyboard]-down->interface :  keys
    c-up->show_image
    c-up->display_switch
    c-down->config
    c-down->filter
    c-down->image
    c-down->command
    config-down-m
    filter-down-m
    image-down-m
    command-down-m
    m-down->db
}
@enduml